# Generated by Django 3.2.7 on 2021-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('picture', models.ImageField(upload_to='pictures/%Y/%m/%d')),
                ('book', models.FileField(upload_to='books/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
