# Generated by Django 3.2.7 on 2021-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210918_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books/%Y-%m-%d', verbose_name='Download the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y-%m-%d', verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Record creation time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Book name'),
        ),
    ]
